### ISSUE TITLE
SlimeVR fails to run on Manjaro KDE Plasma Wayland

### ISSUE THREAD

**Issue by Veragalz** [carl-anders/slimevr-wrangler#43]
```interface 'wl_surface' has no event 2
thread 'main' panicked at 'WaylandSurface failed: ERROR_OUT_OF_HOST_MEMORY', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.14.1/src/vulkan/instance.rs:373:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue 0x564c5de0d5b0 destroyed while proxies still attached:
  xdg_wm_base@20 still attached
  wl_output@14 still attached
  wl_output@13 still attached
  zwp_text_input_manager_v3@12 still attached
  xdg_activation_v1@11 still attached
  wl_subcompositor@10 still attached
  zwp_relative_pointer_manager_v1@9 still attached
  zwp_pointer_constraints_v1@8 still attached
  wl_seat@7 still attached
  wl_shm@6 still attached
  zxdg_decoration_manager_v1@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
```

This is the command line output when trying to run the application with provided instructions.

**Comment by Anti-Apple4life** [comment]
Similar error for me:

```
thread 'main' panicked at library/core/src/panicking.rs:219:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
[1]    258597 IOT instruction (core dumped)  ./slimevr-wrangler
```
Compiled from the latest commit with `cargo clean` and `cargo build`

**Comment by carl-anders** [comment]
The newest version uses updated graphics routines that should work on a larger amount of computers.

If you still have the issue, can you run with `RUST_BACKTRACE=1` so it's possible to see what's the issue, oh, and add some information about the system you're running it on.
